name: abides-39
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - freetype=2.14.1=hce30654_0
  - icu=75.1=hfee45f7_0
  - joblib=0.13.2=py_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libblas=3.9.0=20_osxarm64_openblas
  - libcblas=3.9.0=20_osxarm64_openblas
  - libcxx=21.1.5=hf598326_0
  - libdeflate=1.25=hc11a715_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.9.0=20_osxarm64_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libopenblas=0.3.25=openmp_h6c19121_0
  - libpng=1.6.50=h280e0eb_1
  - libsqlite=3.51.0=h8adb53f_0
  - libtiff=4.7.1=h4030677_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.5=h4a912ad_2
  - matplotlib=3.3.4=py39hdf13c20_0
  - matplotlib-base=3.3.4=py39h3e8bbd8_0
  - ncurses=6.5=h5e97a16_3
  - numpy=1.20.3=py39h54e5778_2
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.6.0=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - pandas=1.2.5=py39h7f752ed_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pillow=11.3.0=py39hfea3036_0
  - pip=25.2=pyh8b19718_0
  - psutil=7.0.0=py39hf3bc14e_0
  - pthread-stubs=0.4=hd74edd7_1002
  - python=3.9.23=h7139b31_0_cpython
  - python_abi=3.9=8_cp39
  - readline=8.2=h1d1bf99_2
  - scipy=1.6.3=py39h5060c3b_0
  - seaborn=0.11.2=hd8ed1ab_0
  - seaborn-base=0.11.2=pyhd8ed1ab_0
  - setuptools=59.8.0=py39h2804cbe_1
  - statsmodels=0.13.5=py39h4d8bf0d_2
  - tk=8.6.13=h892fb3f_3
  - tornado=6.5.2=py39he7485ab_0
  - tqdm=4.36.1=py_0
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - cycler==0.10.0
      - jsons==0.8.8
      - kiwisolver==1.1.0
      - pprofile==2.2.0
      - pyparsing==2.4.0
      - python-dateutil==2.8.0
      - pytz==2019.1
      - six==1.12.0
prefix: /Users/salim/miniconda3/envs/abides-39
